version: 1
services:
  - name: django-app
    type: web
    env:
      - key: DATABASE_URL
        from_secret: db-url
    buildCommand: python manage.py collectstatic --noinput
    startCommand: gunicorn my_resume.wsgi --bind 0.0.0.0:8000