services:
  - name: web
    env:
      - key: SECRET_KEY
        # Add your Django SECRET_KEY value here
        value: "django-insecure-s2q7yu4r=*@db)s03qpm2dpabgr8!*7ycv876asxi))zpxalty"
    build_command: "python manage.py collectstatic --no-input"
    start_command: "gunicorn my_resume.wsgi --bind 0.0.0.0:$PORT"
    health_check_path: "/"

databases:
  - name: my-database
    type: mysql
    plan: free
    config:
      database: portfolio_db_wzx2
      user: samukele
      password: QRh3PQmPIWO0v87YrOOpKr78cPhOiuwM
      host: dpg-chhkpmrhp8ufj5upvpb0-a
      port: 5432