services:
  - name: web
    env:
      - key: SECRET_KEY
        # Add your Django SECRET_KEY value here
        value: "django-insecure-s2q7yu4r=*@db)s03qpm2dpabgr8!*7ycv876asxi))zpxalty"
    build_command: "python manage.py collectstatic --no-input"
    start_command: "gunicorn my_resume.wsgi --bind 0.0.0.0:$PORT"
    health_check_path: "/"

databases:
  - name: my-database
    type: postgresql
    plan: free
    config:
      database: portfolio_db_kvn0
      user: samukele
      password: 0JJNdr4thkKRrwNGW2dvk08hdERVJ1Aq
      host: dpg-cl149nas1bgc73ei26s0-a  # Replace with your PostgreSQL host
      port: 5432