# Generated by Django 4.1.7 on 2023-05-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contactprofile_options_certificate_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
    ]
