[build]
  command = "python manage.py collectstatic --noinput"
  publish = "./staticfiles/"

[build.environment]
  DJANGO_SETTINGS_MODULE = "my_resume.settings.production"

[[plugins]]
  package = "netlify-plugin-cache-next-deploys"
